name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.key }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      - run: cat $HOME/.ssh/key
      # Build
      - run: | 
          cd lameach_digital_garden
          npm ci
          npm run build
      # Deploy
      - run: cd lameach_digital_garden/dist && rsync -e "ssh -p 22 -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --omit-dir-times --no-perms --compress --delete . user@194.156.224.126:/var/www/lameach/html/